In [1]:
import pandas as pd
import os

In [56]:
replace_map = {"ash": 'average_ash_content', "ash_content": 'average_ash_content',\
    "btu": "btu_content", "btucontent": "btu_content", "county_name": "county", \
    "generfuel": "gener_fuel", "plst_st": "plant_state", "plt_name": "plant_name", \
               "plt_st": "plant_state"
              }

def map_if(col):
    if col in replace_map:
        return replace_map[col]
    else:
        return col
    

def format_col_names(cols):



    cols = list(cols)
    cols = [col.lower() for col in cols]
    cols = [col.replace("\n", " ") for col in cols]
    cols = [col.replace(" ", "_") for col in cols]
    #cols = [col for col in cols if "blank" not in col]
    cols = [map_if(col) for col in cols]
    
    return cols

In [37]:
params = {"f4232010.xls": {"skiprows": 6}, "f4232011.xls":{"skiprows": 7}, "f4232008.xls": {"skiprows": 9}, "f4232009.xls": {"skiprows":6}}
dir_ = "ferc_data/"
df = None
all_cols = []
for file in os.listdir(dir_):
    if ".xls" in file:
        #print(file)
        param = {"skip_footer":0}
        if file in params:
            param = params[file]
        df = pd.read_excel(dir_ + file, nrows=1, **param)
        all_cols = all_cols + format_col_names(df.columns)
sorted(list(set(all_cols3)))

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

['ash',
 'ash_content',
 'average_ash_content',
 'average_heat_content',
 'average_sulfur_content',
 'avg_heat_content',
 'blank1',
 'blank2',
 'blank3',
 'blank4',
 'blank5',
 'bom_dist',
 'btu',
 'btu_content',
 'btucontent',
 'co_code',
 'co_name',
 'coalmine_county',
 'coalmine_district',
 'coalmine_fst',
 'coalmine_msha_id',
 'coalmine_name',
 'coalmine_state',
 'coalmine_type',
 'contr_expr',
 'contr_type',
 'contract_exp_date',
 'contract_type',
 'cost',
 'county',
 'county_name',
 'energy_source',
 'expiration',
 'expire',
 'facility_code',
 'fuel_categ',
 'fuel_cost',
 'fuel_group',
 'fuel_type_code',
 'gener_fuel',
 'generfuel',
 'mine_type',
 'month',
 'natural_gas_transportation_service',
 'nerc',
 'operator_code',
 'operator_id',
 'operator_name',
 'orig_st',
 'plant_code',
 'plant_id',
 'plant_name',
 'plant_state',
 'plst_st',
 'plt_code',
 'plt_name',
 'plt_region',
 'plt_st',
 'primary_transportation_mode',
 'prime_mover',
 'purchase_type',
 'quantity',
 'quantity_received',
 'region',
 'regulated',
 'respondent_frequency',
 'revision',
 'secondary_transportation_mode',
 'specf_fuel',
 'state',
 'sulfur',
 'sulfur_content',
 'supplier',
 'survey',
 'unit_type',
 'utility_id',
 'year']

In [38]:
all_cols3 = sorted(list(set(all_cols3)))

In [40]:
all_cols3 = sorted(list(set(format_col_names(all_cols3))))

In [41]:
all_cols3

['average_ash_content',
 'average_heat_content',
 'average_sulfur_content',
 'avg_heat_content',
 'bom_dist',
 'btu_content',
 'co_code',
 'co_name',
 'coalmine_county',
 'coalmine_district',
 'coalmine_fst',
 'coalmine_msha_id',
 'coalmine_name',
 'coalmine_state',
 'coalmine_type',
 'contr_expr',
 'contr_type',
 'contract_exp_date',
 'contract_type',
 'cost',
 'county',
 'energy_source',
 'expiration',
 'expire',
 'facility_code',
 'fuel_categ',
 'fuel_cost',
 'fuel_group',
 'fuel_type_code',
 'gener_fuel',
 'mine_type',
 'month',
 'natural_gas_transportation_service',
 'nerc',
 'operator_code',
 'operator_id',
 'operator_name',
 'orig_st',
 'plant_code',
 'plant_id',
 'plant_name',
 'plant_state',
 'plt_code',
 'plt_region',
 'primary_transportation_mode',
 'prime_mover',
 'purchase_type',
 'quantity',
 'quantity_received',
 'region',
 'regulated',
 'respondent_frequency',
 'revision',
 'secondary_transportation_mode',
 'specf_fuel',
 'state',
 'sulfur',
 'sulfur_content',
 'supplier',
 'survey',
 'unit_type',
 'utility_id',
 'year']

In [62]:
params = {"f4232010.xls": {"skiprows": 6}, "f4232011.xls":{"skiprows": 7}, "f4232008.xls": {"skiprows": 9}, "f4232009.xls": {"skiprows":6}}
dir_ = "ferc_data/"
df = []
all_cols = []
for file in os.listdir(dir_):
    if ".xls" in file:
        #print(file)
        param = {"skip_footer":0}
        if file in params:
            param = params[file]
        df2 = pd.read_excel(dir_ + file, **param)
        df2.columns = format_col_names(df2.columns)
        df2.to_csv("new_" + file)

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [58]:
df.head()

,ASH,ASH_CONTENT,AVG_HEAT_CONTENT,Average_Ash_Content,Average_Heat_Content,Average_Sulfur_Content,BLANK1,BLANK2,BLANK3,BLANK4,BLANK5,BOM_DIST,BTU,BTUCONTENT,BTU_CONTENT,COALMINE_COUNTY,COALMINE_DISTRICT,COALMINE_FST,COALMINE_MSHA_ID,COALMINE_NAME,COALMINE_STATE,COALMINE_TYPE,CONTRACT_EXP_DATE,CONTRACT_TYPE,CONTR_EXPR,CONTR_TYPE,COST,COUNTY,COUNTY_NAME,CO_CODE,CO_NAME,CoalMine_County,CoalMine_MSHA_ID,CoalMine_Name,CoalMine_State,CoalMine_Type,Contract_Exp_Date,Contract_Type,ENERGY_SOURCE,EXPIRATION,EXPIRE,Energy_Source,FACILITY_CODE,FUEL_CATEG,FUEL_COST,FUEL_GROUP,FUEL_TYPE_CODE,Fuel_Cost,Fuel_Group,GENERFUEL,GENER_FUEL,MINE_TYPE,MONTH,Month,NERC,Natural Gas Transportation Service,OPERATOR CODE,OPERATOR NAME,ORIG ST,ORIG_ST,Operator ID,Operator Name,PLANT_CODE,PLANT_NAME,PLANT_STATE,PLST ST,PLT_CODE,PLT_NAME,PLT_REGION,PLT_ST,PRIME_MOVER,PURCHASE_TYPE,Plant ID,Plant Name,Primary Transportation Mode,QUANTITY,QUANTITY_RECEIVED,Quantity,REGION,REGULATED,RESPONDENT_FREQUENCY,REVISION,Regulated,Respondent_Frequency,SPECF_FUEL,SULFUR,SULFUR_CONTENT,SUPPLIER,SURVEY,Secondary Transportation Mode,State,Supplier,UNIT_TYPE,UTILITY_ID,YEAR,Year,average_ash_content,average_heat_content,average_sulfur_content,avg_heat_content,bom_dist,btu_content,co_code,co_name,coalmine_county,coalmine_district,coalmine_fst,coalmine_msha_id,coalmine_name,coalmine_state,coalmine_type,contr_expr,contr_type,contract_exp_date,contract_type,cost,county,energy_source,expiration,expire,facility_code,fuel_categ,fuel_cost,fuel_group,fuel_type_code,gener_fuel,mine_type,month,natural_gas_transportation_service,nerc,operator_code,operator_id,operator_name,orig_st,plant_code,plant_id,plant_name,plant_state,plt_code,plt_region,primary_transportation_mode,prime_mover,purchase_type,quantity,quantity_received,region,regulated,respondent_frequency,revision,secondary_transportation_mode,specf_fuel,state,sulfur,sulfur_content,supplier,survey,unit_type,utility_id,year
0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,25.122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,186.9,73.0,Jefferson,195.0,Alabama Power Co,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coal,NaN,U,1.0,NaN,NaN,NaN,NaN,NaN,AL,NaN,NaN,NaN,NaN,NaN,NaN,AL,3.0,Barry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BIT,0.81,NaN,Supplier Record Number 1,FERC423,NaN,NaN,NaN,NaN,NaN,2002.0,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,NaN,23.564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,133.4,999.0,County Unknown,195.0,Alabama Power Co,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coal,NaN,S,1.0,NaN,NaN,NaN,NaN,NaN,IM,NaN,NaN,NaN,NaN,NaN,NaN,AL,3.0,Barry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BIT,0.64,NaN,Supplier Record Number 1,FERC423,NaN,NaN,NaN,NaN,NaN,2002.0,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,NaN,23.564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,133.4,999.0,County Unknown,195.0,Alabama Power Co,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coal,NaN,U,1.0,NaN,NaN,NaN,NaN,NaN,IM,NaN,NaN,NaN,NaN,NaN,NaN,AL,3.0,Barry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BIT,0.64,NaN,Supplier Record Number 1,FERC423,NaN,NaN,NaN,NaN,NaN,2002.0,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,4.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,NaN,23.614,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,153.9,999.0,County Unknown,195.0,Alabama Power Co,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coal,NaN,S,1.0,NaN,NaN,NaN,NaN,NaN,IM,NaN,NaN,NaN,NaN,NaN,NaN,AL,3.0,Barry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184133.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BIT,0.60,NaN,Supplier Record Number 2,FERC423,NaN,NaN,NaN,NaN,NaN,2002.0,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,4.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,NaN,23.614,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,153.9,999.0,County Unknown,195.0,Alabama Power Co,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coal,NaN,U,1.0,NaN,NaN,NaN,NaN,NaN,IM,NaN,NaN,NaN,NaN,NaN,NaN,AL,3.0,Barry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BIT,0.60,NaN,Supplier Record Number 2,FERC423,NaN,NaN,NaN,NaN,NaN,2002.0,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [9]:
dir_ = "ferc_data/"
df = []
all_cols = []
for file in os.listdir(dir_):
    if "new_" in file:
        df2 = pd.read_csv(dir_ + file)
        if len(df):
            for col in all_cols:
                if col not in df2.columns:
                    df2[col] = None
            df.append(df2[all_cols])
        else:
            df = df2
            all_cols = df.columns

/Users/lhinkesjones/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
df.head()

,Unnamed: 0,co_code,plt_code,year,month,bom_dist,orig_st,mine_type,plt_region,plant_state,blank3,gener_fuel,specf_fuel,blank4,contr_type,contr_expr,quantity,btu_content,sulfur,average_ash_content,cost,blank5,unit_type,county
0,0,189,56,2000,1,NaN,NaN,NaN,6,1,NaN,2,FO2,NaN,7,9,341,130500,0.10,0.00,560.7,NaN,1,NaN
1,1,189,56,2000,1,8.0,54.0,U,6,1,NaN,1,BIT,NaN,7,9,9659,12123,0.77,12.72,143.3,NaN,1,39.0
2,2,189,56,2000,1,10.0,17.0,U,6,1,NaN,1,BIT,NaN,7,9,28520,11756,1.35,5.82,138.3,NaN,1,81.0
3,3,189,56,2000,1,13.0,1.0,U,6,1,NaN,1,BIT,NaN,1,0,55576,11838,1.58,13.04,130.8,NaN,1,57.0
4,4,189,56,2000,1,45.0,3.0,U,6,1,NaN,1,BIT,NaN,7,9,47775,11767,0.45,3.90,139.8,NaN,1,999.0

In [12]:
df = df.drop(columns=["blank3", "blank4", "blank5", "Unnamed: 0"])

In [13]:
df.isna().sum()/len(df)

co_code                0.000000
plt_code               0.000000
year                   0.000000
month                  0.000000
bom_dist               0.436446
orig_st                0.436446
mine_type              0.436446
plt_region             0.000000
plant_state            0.000000
gener_fuel             0.000000
specf_fuel             0.000000
contr_type             0.000000
contr_expr             0.000000
quantity               0.000000
btu_content            0.000000
sulfur                 0.000000
average_ash_content    0.000000
cost                   0.000000
unit_type              0.000000
county                 0.436676
dtype: float64

In [14]:
df.to_csv("all.csv")